name: Frontend Tests
on:
  push:
    branches:
      - team1-ayush
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Dependencies
     # working-directory: ./frontend
      working-directory: ./e2e-tests

      run: npm install
    
    # - name: Run unit tests
    #   working-directory: ./frontend
    #   run: npm run test:unit
    
    # - name: Run integration tests
    #   working-directory: ./frontend
    #   run: npm run test:integration
    
   # - name: Run all tests with coverage
    #  working-directory: ./frontend
     # run: npm test

    name: Run e2e test
      working-directory: ./e2e-tests
      run: npx cypress run